Web:
- src/main/resources/templates/freemarker/*.ftlh
- src/main/resources/templates/freemarker/style.css

Continuous integration:
- .github/**/*
- .github/*
- .pre-commit-config.yaml
- ci_settings.xml
