name: Publish a new release

on:
  push:
    branches:
    - feat/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: adopt
        cache: maven
    - name: Build with Maven
      run: mvn --batch-mode -DskipTests package --update-snapshots verify

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugins: |
          "semantic-release-config-gitmoji"
          "semantic-release-maven --legacy-peer-deps"
        extends: semantic-release-config-gitmoji
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
