name: Publish a new release

on:
  workflow_dispatch:
    inputs:
      is_major:
        type: boolean
        required: false
        description: Make a major version
      breaking_changes:
        type: string
        required: false
        description: Breaking changes message

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: adopt
        cache: maven

    - name: Build with Maven
      run: mvn --batch-mode -DskipTests package --update-snapshots verify


  prepare-major:
    name: Prepare for a new major version
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.get-last-commit-ref.outputs.ref }}
    if: ${{ github.event.inputs.isMajor == 'true' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Get last commit message
      id: last-commit-message
      run: |
        echo "::set-output name=msg::$(git log -1 --pretty=%s)"

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "${{ steps.last-commit-message.outputs.msg }}\n BREAKING CHANGE ${{ github.event.inputs.message }}"
        commit_options: --amend --allow-empty
        skip_dirty_check: true
        push_options: --force

    - id: get-last-commit-ref
      run: |
        echo "::set-output name=ref::$(git rev-parse HEAD)"

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: prepare-major
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ needs.prepare-major.outputs.output1 }}

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        extra_plugins: |
          "semantic-release-config-gitmoji"
        extends: semantic-release-config-gitmoji
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
