name: release

on:
  push:
    branches:
      - feat/CI_release
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-m2-
      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: test
          path: target/*
  build_release:
      needs: run_tests
      runs-on: ubuntu-latest
      if: "!contains(github.event.head_commit.message, '[ci skip]')"
      steps:
        - uses: actions/checkout@v2
        - name: Cache Maven packages
          uses: actions/cache@v2
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
              ${{ runner.os }}-m2-
        - name: Build
          uses: qcastel/github-actions-maven-cmd@master
          with:
            maven-args: "clean install -Ddockerfile.skip -DdockerCompose.skip -Djib.skip"
        - name: Release
          uses: qcastel/github-actions-maven-release@master
          env:
            JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
          with:
            gpg-enabled: true
            gpg-key-id: ${{ secrets.GPG_KEY_ID }}
            gpg-key: ${{ secrets.GPG_KEY }}
            release-branch-name: "feat/CI_release"
            version-major: true
            git-release-bot-name: "ipponbot"
            git-release-bot-email: "bot@idhub.io"
            maven-args: "-Dmaven.javadoc.skip=true -DskipTests -DskipITs -Dmaven.deploy.skip=true"

            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.2.4
          with:
            name: build
            path: target/*
