name: release

on:
  push:
    branches:
      - feat/CI_release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
          server-id: github
          server-username: ${{ secrets.GIT_BOT_USERNAME }}
          server-password: ${{ secrets.GIT_TOKEN }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-m2-
      - name: Maven Release
        run: |
          git config --global user.email "${{ secrets.GIT_BOT_EMAIL }}"
          git config --global user.name "Github CI"
          mvn $MAVEN_CLI_OPTS release:clean -DskipTests=true
          mvn $MAVEN_CLI_OPTS build-helper:parse-version versions:set \
          release:prepare DskipTests=true \ -DdevelopmentVersion =\${parsedVersion.nextMajorVersion}.\${parsedVersion.minorVersion}-SNAPSHOT \
          -DnewVersion =\${parsedVersion.nextMajorVersion}.\${parsedVersion.minorVersion}-SNAPSHOT
          release:perform DskipTests=true
