name: release

on:
  push:
    branches:
      - feat/CI_release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-m2-
      - name: Maven Release
        run: |
          mvn $MAVEN_CLI_OPTS release:clean -DskipTests=true
          mvn $MAVEN_CLI_OPTS build-helper:parse-version versions:set \
          release:prepare DskipTests=true \ -DdevelopmentVersion =\${parsedVersion.nextMajorVersion}.\${parsedVersion.minorVersion}-SNAPSHOT \
          release:perform DskipTests=true
        env:
          MAVEN_CLI_OPTS: -s ci_settings.xml -B -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
          GITHUB_USERNAME: ipponbot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
